apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-system
  namespace: calico-system
---
apiVersion: v1
kind: Secret
metadata:
  name: calico-system-secret
  annotations:
    kubernetes.io/service-account.name: calico-system
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-system
rules:
  - apiGroups: [""]
    # All resource types (pods, services, etc.) in the core API group
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-system-binding
subjects:
  - kind: ServiceAccount
    name: calico-system
    namespace: calico-system
roleRef:
  kind: ClusterRole
  name: calico-system
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-router
  labels:
    app: calico-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calico-router
  template:
    metadata:
      labels:
        app: calico-router
    spec:
      serviceAccountName: calico-system
      containers:
      - name: calico-router
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        env:
        # Store the state in a k8s secret
        - name: TS_KUBE_SECRET
          value: "calico-system"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: calico-system
              key: TS_AUTHKEY
              optional: true
        - name: TS_ROUTES
          value: "10.22.0.0/16"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          privileged: true
